import { VeterinaryService } from './service.model';

export const VETERINARY_SERVICES: readonly VeterinaryService[] = [
  {
    slug: 'consultas-veterinarias',
    name: 'Consultas veterinarias',
    summary: 'Evaluación integral y orientación profesional para cada etapa de su vida.',
    description: 'Realizamos una evaluación clínica completa, resolvemos tus dudas y planteamos un plan de cuidado personalizado para tu mascota.',
    category: 'Consultas y prevención',
    imageUrl: 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Veterinaria examinando a un perro durante una consulta',
    icon: 'medical_services',
    featured: true,
  },
  {
    slug: 'tratamientos',
    name: 'Tratamientos',
    summary: 'Planes terapéuticos seguros con seguimiento cercano de la recuperación.',
    description: 'Indicamos tratamientos adaptados al diagnóstico, edad y condición de cada paciente, con controles para acompañar su evolución.',
    category: 'Tratamientos y cirugía',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Profesional veterinaria preparando un tratamiento',
    icon: 'healing',
  },
  {
    slug: 'desparasitacion',
    name: 'Desparasitación',
    summary: 'Protección periódica frente a parásitos internos y externos.',
    description: 'Diseñamos calendarios de desparasitación según especie, peso, edad y estilo de vida para proteger a tu mascota y a tu familia.',
    category: 'Consultas y prevención',
    imageUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro pequeño recibiendo cuidado preventivo',
    icon: 'shield',
  },
  {
    slug: 'vacunacion',
    name: 'Vacunación',
    summary: 'Programas de vacunación para una protección completa y oportuna.',
    description: 'Aplicamos vacunas con protocolos actualizados y te ayudamos a mantener al día el calendario preventivo de tu compañero.',
    category: 'Consultas y prevención',
    imageUrl: 'https://images.unsplash.com/photo-1612536057832-2ff7ead58194?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Gato atendido cuidadosamente en una clínica veterinaria',
    icon: 'vaccines',
  },
  {
    slug: 'internamientos',
    name: 'Internamientos',
    summary: 'Vigilancia clínica y cuidados continuos durante la recuperación.',
    description: 'Brindamos observación, medicación y cuidados personalizados en un entorno tranquilo para pacientes que requieren seguimiento.',
    category: 'Hospitalización y cuidados',
    imageUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro descansando durante su recuperación',
    icon: 'bed',
  },
  {
    slug: 'profilaxis-dental',
    name: 'Profilaxis dental',
    summary: 'Limpieza profesional para prevenir sarro y enfermedad periodontal.',
    description: 'Cuidamos la salud oral con evaluación, limpieza dental y recomendaciones para mantener una higiene adecuada en casa.',
    category: 'Consultas y prevención',
    imageUrl: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro mostrando una dentadura saludable',
    icon: 'dentistry',
  },
  {
    slug: 'cirugia-general',
    name: 'Cirugía general',
    summary: 'Procedimientos quirúrgicos con evaluación y monitoreo profesional.',
    description: 'Realizamos cirugías programadas con valoración preoperatoria, monitoreo durante el procedimiento y seguimiento posoperatorio.',
    category: 'Tratamientos y cirugía',
    imageUrl: 'https://images.unsplash.com/photo-1599443015574-be5fe8a05783?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Equipo médico preparado para un procedimiento veterinario',
    icon: 'surgery',
  },
  {
    slug: 'cirugia-dental',
    name: 'Cirugía dental',
    summary: 'Atención especializada para afecciones complejas de la cavidad oral.',
    description: 'Tratamos piezas dañadas y problemas orales que requieren intervención, priorizando el control del dolor y la recuperación.',
    category: 'Tratamientos y cirugía',
    imageUrl: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro tranquilo durante una revisión veterinaria',
    icon: 'oral_surgery',
  },
  {
    slug: 'laboratorio-clinico',
    name: 'Laboratorio clínico',
    summary: 'Análisis que apoyan diagnósticos rápidos y decisiones precisas.',
    description: 'Procesamos pruebas clínicas para conocer el estado de salud del paciente y orientar oportunamente su tratamiento.',
    category: 'Diagnóstico',
    imageUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Muestras preparadas para análisis de laboratorio',
    icon: 'science',
  },
  {
    slug: 'farmacia-veterinaria',
    name: 'Farmacia veterinaria',
    summary: 'Productos veterinarios seleccionados con orientación profesional.',
    description: 'Encuentra medicamentos y productos para el cuidado de tu mascota, siempre con indicaciones responsables de nuestro equipo.',
    category: 'Servicios especiales',
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Productos organizados en una farmacia',
    icon: 'medication',
  },
  {
    slug: 'ecografia',
    name: 'Ecografía',
    summary: 'Evaluación por imágenes no invasiva para órganos y tejidos internos.',
    description: 'Obtenemos imágenes en tiempo real para apoyar el diagnóstico de alteraciones abdominales, gestacionales y de tejidos blandos.',
    category: 'Diagnóstico',
    imageUrl: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Equipo moderno para diagnóstico por imágenes',
    icon: 'ultrasound',
  },
  {
    slug: 'rayos-x',
    name: 'Rayos X',
    summary: 'Imágenes radiográficas para evaluar huesos, tórax y abdomen.',
    description: 'El estudio radiográfico permite identificar lesiones y alteraciones internas para definir el manejo más adecuado.',
    category: 'Diagnóstico',
    imageUrl: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Veterinario revisando imágenes diagnósticas',
    icon: 'radiology',
  },
  {
    slug: 'servicio-a-domicilio',
    name: 'Servicio a domicilio',
    summary: 'Atención veterinaria coordinada en la comodidad de tu hogar.',
    description: 'Acercamos determinados cuidados y evaluaciones a casa para mascotas que se estresan al trasladarse o tienen movilidad limitada.',
    category: 'Servicios especiales',
    imageUrl: 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Familia cuidando a su perro en casa',
    icon: 'home_health',
  },
  {
    slug: 'hospedaje',
    name: 'Hospedaje',
    summary: 'Un espacio seguro, cómodo y supervisado durante tu ausencia.',
    description: 'Tu mascota recibe alojamiento, alimentación, paseos y atención cercana para que se sienta acompañada mientras estás fuera.',
    category: 'Hospitalización y cuidados',
    imageUrl: 'https://images.unsplash.com/photo-1601758064226-0c3e4f1e7fc1?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro cómodo en un espacio de hospedaje',
    icon: 'pet_hotel',
  },
  {
    slug: 'microchips',
    name: 'Microchips',
    summary: 'Identificación permanente para facilitar el regreso seguro a casa.',
    description: 'Implantamos un dispositivo de identificación pequeño y seguro que vincula a tu mascota con sus datos responsables.',
    category: 'Servicios especiales',
    imageUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro con placa de identificación',
    icon: 'memory',
  },
  {
    slug: 'traumatologia',
    name: 'Traumatología',
    summary: 'Evaluación y manejo de lesiones óseas, articulares y musculares.',
    description: 'Atendemos alteraciones del movimiento y traumatismos con diagnóstico, control del dolor y un plan de recuperación.',
    category: 'Tratamientos y cirugía',
    imageUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Perro activo durante una evaluación de movilidad',
    icon: 'orthopedics',
  },
  {
    slug: 'urgencias-24-horas',
    name: 'Urgencias 24 horas',
    summary: 'Respuesta inmediata para situaciones que no pueden esperar.',
    description: 'Nuestro canal de urgencias está disponible las 24 horas. Si tu mascota presenta una emergencia, llámanos antes de acudir para orientarte.',
    category: 'Hospitalización y cuidados',
    imageUrl: 'https://images.unsplash.com/photo-1516841273335-e39b37888115?auto=format&fit=crop&w=900&q=80',
    imageAlt: 'Equipo veterinario disponible para atención de urgencia',
    icon: 'emergency',
    emergency: true,
  },
];
